baseURL: 'https://rizin.re/'
title: Rizin
paginate: 10
theme: hugo-PaperMod

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

minify:
  disableXML: true
  minifyOutput: true

menu:
    main:
      - name: Blog
        url: /posts/
        weight: 5
      - name: Organization
        url: /organization/
        weight: 10
      - name: Cutter
        url: https://cutter.re
        weight: 15
        
params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: Rizin
  description: 'Rizin Is a Free and Open Source Reverse Engineering Platform'
  author: Rizin
  # author: ["Me", "You"] # multiple authors

  images: 
    - /images/rizin_preview.png

  ShowReadingTime: true
  ShowShareButtons: true
  comments: false
  # dark, light, auto
  defaultTheme: auto
  disableThemeToggle : false
  disableSpecial1stPost : false

  assets:
    favicon: '/favicon-32x32.png'

  label:
    text: "Rizin"
    iconHeight: 35

  # profile-mode
  profileMode:
    enabled: False # needs to be explicitly set
    title: Rizin
    subtitle: "Free and Open Source Reverse Engineering Platform"
    imageUrl: '/images/rizin.svg'
    # imageTitle: my image
    buttons:
      - name: Blog
        url: posts
      - name: Tags
        url: tags

  # home-info mode
  homeInfoParams:
    Title: "Hi there \U0001F44B"
    Content: Free and Open Source Reverse Engineering Platform

  socialIcons:
    - name: twitter
      url: 'https://twitter.com/rizinorg'
    - name: github
      url: 'https://github.com/rizinorg'
